### ISSUE TITLE
Question about the model evaluation with full-sort setting

### ISSUE THREAD

**Issue by nidohsp** [zfan20/MStein#3]
Thanks for your great work. I notice that you mask user historical interaction in the evaluation phase (same as S3rec):
https://github.com/zfan20/MStein/blob/47b5bd70f8d126dbb2abba18b7d0f1f9c54ea406/trainers.py#L1453-L1454

I want to know the rationality of this setting?  I think this setting is actually still equivalent to negative sampling, and is strange for seq recommendation as mentioned by [others](https://github.com/Woeee/FMLP-Rec/issues/4). 

Anyhow, It seems fair since you use this setting for all baselines, and not affect the robustness of your paper.  I just want to know your opinion.

**Comment by zfan20** [comment]
Hi, thanks for bringing this up. The answer is the history of the RecSys research community. It has been the default setting since a long time ago for a great amount of classical work. 

This is not equivalent to negative sampling. As you might know, the item catalog size is typically in >>> 10K, while user interactions are typically short, in the scale of 100, most are < 100. 10K - 100 is almost no difference with 10K, even item catalog can be much higher..., such 1M. 

One more thing if you also include interacted items in the recommendation list is that the scores of these ranked interacted items are already trained to be much higher than others without interactions, i.e., encouraging re-purchase behaviors.

**Comment by nidohsp** [comment]
Thx for your timely and clear response. 

As I know, history masking is the basic setting for general recommendation task. Since one main goal for seq recommendation is to recommend appropriate items at appropriate time, few works for seq rec (except s3rec and works based on it) adopted this setting. Besides, some widely used libs (such as recbole) also abandoned this setting. 

I think your answer is convincing, I raised this question since nowadays many works say they adopt full-sort rank in evaluation phase but using these two settings indiscriminately, which is very confusing.

**Comment by zfan20** [comment]
Just one humble opinion, widely used libs might also have some issues, such as the number of negatives for training. Using binary cross-entropy (one negative item, typical way in recsys research) and cross-entropy (all items as training negatives, default setting in some libs) has huge performance differences, without any model architecture change.

I will close this comment if you have no further questions.
